---
title: "Temporal biotic homogenisation patterns vary with taxa"
date: "`r Sys.Date()`"
output:
  rmdformats::html_clean:
    highlight: kate
    toc: TRUE
    toc_depth: 2
    toc_float: TRUE
    number_sections: TRUE
---

```{r setup, include=FALSE}
## Global options
knitr::opts_chunk$set(cache = TRUE)
```


# Data management

## Package
Load packages
```{r}
pacman::p_load(
  tidyverse,                   # data management
  lme4, lmerTest, broom,       # GLM
  ggeffects, patchwork, ggsci, gridExtra, # ggplot
  vegan, iNEXT, betapart       # composition
  )
```


## load data
```{r}
df_plant     <- read_csv("data/df_plant_output.csv", show_col_types = FALSE)
df_bird      <- read_csv("data/df_bird_output.csv", show_col_types = FALSE)
df_butterfly <- read_csv("data/df_butterfly_output.csv", show_col_types = FALSE)
```

# Fig. 1

## Rarafaction curve
Function of iNEXT 
```{r}
est_inext <- function(x) {
  
  past <- x %>% 
    dplyr::select(site, time, sciname, value) %>% 
    dplyr::filter(time == "past") %>% 
    pivot_wider(names_from = site, values_from = value) %>% 
    dplyr::mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) %>% 
    dplyr::filter(rowSums(across(where(is.numeric)), na.rm = TRUE) >= 0) %>% 
    column_to_rownames("sciname") %>% 
    dplyr::select(-time) 
  
  present <- x %>% 
    dplyr::select(site, time, sciname, value) %>% 
    dplyr::filter(time == "now") %>% 
    pivot_wider(names_from = site, values_from = value) %>% 
    dplyr::mutate(across(everything(), ~ ifelse(is.na(.), 0, .))) %>% 
    dplyr::filter(rowSums(across(where(is.numeric)), na.rm = TRUE) > 0) %>% 
    column_to_rownames("sciname") %>% 
    dplyr::select(-time) 
  
  
  # list for inext
  list_inext <- list("Past" = past, "Present" = present) 
  
  
  # doing 
  iNEXT(list_inext, q = 0, datatype = "incidence_raw")
  
}
```

## Run iNext
```{r}
## Plant
df_plant %>% {
  
  # All species
  est_inext(.) ->> inext_plant
  
  # Native species
  dplyr::filter(., exotic == "Native") %>% 
    est_inext(.) ->> inext_plant_n
  
  }


## Bird
df_bird %>% {
  
  # All species
  est_inext(.) ->> inext_bird
  
  # Native species
  dplyr::filter(., exotic == "Native") %>% 
    est_inext(.) ->> inext_bird_n
  }


## Butterfly
df_butterfly %>% {
  
  # All species
  est_inext(.) ->> inext_butterfly
  
  # Native species
  dplyr::filter(., exotic == "Native") %>% 
    est_inext(.) ->> inext_butterfly_n
  }
```

## Plot rare factrion curve
```{r message=FALSE, warning=FALSE}
# Plant
p_inext_plant <-
  ggiNEXT(inext_plant) +
    labs(
      title = "Plant",
      y = "All species richness"
      ) +
    scale_color_manual(values = c("#00AFBB", "#E7B800")) +
    scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
    scale_x_continuous(limits = c(0, 30)) +
    theme_bw(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      axis.title.x = element_blank(),
      plot.subtitle = element_text(hjust = 0.5, size = 10),
      legend.position = "none"
      )


# Native plant
p_inext_plant_n <-
  ggiNEXT(inext_plant_n) +
    labs(
      x = "",
      y = "Native species richness"
      ) +
    scale_color_manual(values = c("#00AFBB", "#E7B800")) +
    scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
    scale_x_continuous(limits = c(0, 30)) +
    theme_bw(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      plot.subtitle = element_text(hjust = 0.5, size = 10),
      legend.position = "none"
      )




# Bird
p_inext_bird <-
  ggiNEXT(inext_bird) +
    labs(title = "Bird") +
    scale_color_manual(values = c("#00AFBB", "#E7B800")) +
    scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
    scale_x_continuous(limits = c(0, 15)) +
    theme_bw(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none"
      )



# Native bird
p_inext_bird_n <-
  ggiNEXT(inext_bird_n) +
    labs(x = "Number of sites") +
    scale_color_manual(values = c("#00AFBB", "#E7B800")) +
    scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
    scale_x_continuous(limits = c(0, 15)) +
    theme_bw(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none"
      )



# Butterfly
p_inext_butterfly <-
  ggiNEXT(inext_butterfly) +
    labs(title = "Butterfly") +
    scale_color_manual(values = c("#00AFBB", "#E7B800")) +
    scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
    scale_x_continuous(limits = c(0, 15)) +
    theme_bw(base_size = 8) +
    theme(
      panel.grid = element_blank(),
      axis.title.x = element_blank(),
      axis.title.y = element_blank(),
      legend.position = "none"
      )


# Native butterfly
p_inext_butterfly_n <-
  ggiNEXT(inext_butterfly_n) +
  labs(
    x = "",
    y = "Species richness"
  ) +
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  scale_x_continuous(limits = c(0, 15)) +
  theme_bw(base_size = 8) +
  theme(
    panel.grid = element_blank(),
    axis.title.y = element_blank(),
    legend.position = "none"
    )
```

Plot combine
```{r warning=FALSE}
# Extract a legend
p_legend <- inext_butterfly_n %>% 
  ggiNEXT() + 
  scale_color_manual(values = c("#00AFBB", "#E7B800")) +
  scale_fill_manual(values = c("#00AFBB", "#E7B800")) +
  theme(
    legend.direction = "vertical",
    legend.text = element_text(size = 8),
    legend.key.size = unit(0.5, 'cm'))

legend_inext <- p_legend %>% 
  ggpubr::get_legend() %>% 
  ggpubr::as_ggplot()


# Axis label
grid.arrange(
  p_inext_plant,  p_inext_bird, p_inext_butterfly,
  p_inext_plant_n, p_inext_bird_n, p_inext_butterfly_n,
  legend_inext,
  nrow = 2,
  layout_matrix = rbind(c(1, 2, 3, 7),
                        c(4, 5, 6, 7)),
  widths = c(1.05, 1, 0.95, 0.7),
  heights = c(1, 1)
  ) 
```





